sudo: required

language: python

python:
  - "3.6"

env:
  global: SCIDB_VER=18.1
  matrix:
    - IMG=debian:8      TARGET=deb
    - IMG=ubuntu:trusty TARGET=deb
    - IMG=centos:6      TARGET=rpm

services:
  - docker

before_install:
  - docker run
    --name scidb
    --detach
    --env SCIDB_VER=${SCIDB_VER}
    --env SCIDB_INSTALL_PATH=/opt/scidb/${SCIDB_VER}
    --volume `pwd`:/this
    ${IMG}

script:
  - docker exec scidb sh /this/setup.sh
  - docker exec scidb /this/extra-scidb-libs.sh
    $TARGET
    /root
    /tmp
    1
