branches:
  only:
  - gh-pages
  - /.*/

os: linux

language: python

python:
  - "3.6"

env:
  global:
    - SCIDB_VER=19.11
    - PKG_VER=2
  jobs:
    - BUILD_IMG=ubuntu:xenial
      DEPLOY_IMG=-xenial
      TARGET=deb
    - BUILD_IMG=centos:7
      DEPLOY_IMG=-centos-7
      TARGET=rpm

services:
  - docker

before_script:
  - docker run
    --detach
    --env SCIDB_INSTALL_PATH=/opt/scidb/$SCIDB_VER
    --env SCIDB_VER=$SCIDB_VER
    --name script
    --rm
    --tty
    --volume `pwd`:/this
    $BUILD_IMG

  - docker run
    --detach
    --name deploy
    --rm
    --tty
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    --volume `pwd`:/this
    rvernica/scidb:$SCIDB_VER$DEPLOY_IMG

  - if [ "$DEPLOY_IMG" = "-centos-7" ]; then
      docker exec deploy /opt/scidb/19.11/bin/scidbctl.py start scidb
    fi

script:
  - docker exec script sh /this/setup.sh
  - docker exec script /this/extra-scidb-libs.sh
    $TARGET
    /root
    /this
    $PKG_VER

  - if [ "$TARGET" = "deb" ]; then
      docker exec deploy sed --in-place
        "\#deb http://deb.debian.org/debian jessie-updates main#d"
        /etc/apt/sources.list;
    fi
  - docker exec deploy sh /this/install.sh --only-prereq
  - if [ "$DEPLOY_IMG" = "-centos-7" ]; then
      docker exec deploy /opt/scidb/$SCIDB_VER/bin/scidbctl.py start scidb;
    fi
  - if [ "$TARGET" = "rpm" ]; then
      docker exec deploy yum install --assumeyes
        /this/extra-scidb-libs-$SCIDB_VER-$PKG_VER-1.x86_64.rpm;
    else
      docker exec deploy apt-get install
        --assume-yes
        --no-install-recommends
        libarrow0;
      docker exec deploy dpkg --install
        /this/extra-scidb-libs-$SCIDB_VER-$PKG_VER.deb;
    fi
  - docker exec deploy sh /this/try.sh

after_script:
  - docker stop script
  - docker stop deploy
