branches:
  only:
  - gh-pages
  - /.*/

os: linux

language: python

python:
  - "3.6"

env:
  global: SCIDB_VER=19.11
  jobs:
    - IMG=-xenial   INSTALL=
    - IMG=-xenial   INSTALL=--github
    - IMG=-centos-7 INSTALL=
    - IMG=-centos-7 INSTALL=--github

services:
  - docker

install:
  - docker run
    --detach
    --name container
    --rm
    --tty
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    rvernica/scidb:${SCIDB_VER}${IMG}

  - if [ "$IMG" = "-centos-7" ]; then
      docker exec container /opt/scidb/$SCIDB_VER/bin/scidbctl.py start scidb ;
    fi

script:
  - docker exec container sh -c
    "wget -O- https://paradigm4.github.io/extra-scidb-libs/install.sh
     |  sh -s -- $INSTALL"
  - docker exec container sh -c
    "wget -O- https://paradigm4.github.io/extra-scidb-libs/try.sh
     |  sh"

  - if [ "$IMG" = "-centos-7" ]; then
      docker exec container yum remove --assumeyes
        extra-scidb-libs-$SCIDB_VER ;
    else
      docker exec container apt-get remove --assume-yes --purge
        extra-scidb-libs-$SCIDB_VER ;
    fi
