branches:
  only:
  - gh-pages
  - /.*/

os: linux

language: python

python:
  - "3.6"

env:
  global: SCIDB_VER=19.11
  jobs:
    - IMG=-xenial   INSTALL=         ENTRYPOINT=/sbin/init
    - IMG=-xenial   INSTALL=--github ENTRYPOINT=/sbin/init
    - IMG=-centos-7 INSTALL=         ENTRYPOINT=/docker-entrypoint.sh
    - IMG=-centos-7 INSTALL=--github ENTRYPOINT=/docker-entrypoint.sh

services:
  - docker

install:
  - docker run
    --cap-add SYS_ADMIN
    --detach
    --entrypoint $ENTRYPOINT
    --name container
    --rm
    --tty
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    rvernica/scidb:${SCIDB_VER}${IMG}

  - docker exec container /opt/scidb/$SCIDB_VER/bin/scidbctl.py start scidb

script:
  - docker exec container sh -c
    "wget -O- https://paradigm4.github.io/extra-scidb-libs/install.sh
     |  sh -s -- $INSTALL"
  - docker exec container sh -c
    "wget -O- https://paradigm4.github.io/extra-scidb-libs/try.sh
     |  sh"
