sudo: required

language: python

python:
  - "3.6"

env:
  global: SCIDB_VER=18.1
  matrix:
    - IMG=debian:8                              TARGET=deb
    - IMG=ubuntu:trusty                         TARGET=deb
    - IMG=centos:6                              TARGET=rpm
    - IMG=rvernica/scidb:${SCIDB_VER}           TARGET=try
    - IMG=rvernica/scidb:${SCIDB_VER}-trusty    TARGET=try
    - IMG=rvernica/scidb:${SCIDB_VER}-centos-6  TARGET=try
    - IMG=rvernica/scidb:${SCIDB_VER}-centos-7  TARGET=try

services:
  - docker

before_install:
  - docker run
    --name container
    --detach
    --tty
    --env SCIDB_VER=${SCIDB_VER}
    --env SCIDB_INSTALL_PATH=/opt/scidb/${SCIDB_VER}
    --volume `pwd`:/this
    ${IMG}

script:
  - if [ "${TARGET}" = "deb" -o "${TARGET}" = "rpm" ]; then
    docker exec container sh /this/setup.sh;
    docker exec container /this/extra-scidb-libs.sh
    $TARGET
    /root
    tmp
    1;
    fi
  - if [ "${TARGET}" = "try" ]; then
    docker exec container sh -c
    "wget -O - https://paradigm4.github.io/extra-scidb-libs/install.sh | sh";
    docker exec container sh -c
    "wget -O - https://paradigm4.github.io/extra-scidb-libs/try.sh | sh";
    fi
