branches:
  only:
  - gh-pages
  - /.*/

os: linux

language: python

python:
  - "3.6"

env:
  global:
    - SCIDB_VER=19.11
    - PKG_VER=4
  jobs:
    - BUILD_IMG=ubuntu:xenial
      DEPLOY_IMG=-xenial
      TARGET=deb
      ENTRYPOINT=/sbin/init
    - BUILD_IMG=centos:7
      DEPLOY_IMG=-centos-7
      TARGET=rpm
      ENTRYPOINT=/docker-entrypoint.sh

services:
  - docker

before_script:
  - docker run
    --detach
    --env SCIDB_INSTALL_PATH=/opt/scidb/$SCIDB_VER
    --env SCIDB_VER=$SCIDB_VER
    --name script
    --rm
    --tty
    --volume `pwd`:/this
    $BUILD_IMG

  - docker run
    --cap-add SYS_ADMIN
    --detach
    --entrypoint $ENTRYPOINT
    --name deploy
    --rm
    --tty
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    --volume `pwd`:/this
    rvernica/scidb:$SCIDB_VER$DEPLOY_IMG

  - docker exec deploy /opt/scidb/$SCIDB_VER/bin/scidbctl.py start scidb

script:
  - docker exec script sh /this/setup.sh
  - docker exec script /this/extra-scidb-libs.sh
    $TARGET
    /root
    /this
    $PKG_VER

  - docker exec deploy sh /this/install.sh --only-prereq
  - if [ "$TARGET" = "rpm" ]; then
      docker exec deploy yum install --assumeyes
        /this/extra-scidb-libs-$SCIDB_VER-$PKG_VER-1.x86_64.rpm ;
    else
      docker exec deploy apt-get install
        --assume-yes
        --no-install-recommends
        libarrow0 ;
      docker exec deploy dpkg --install
        /this/extra-scidb-libs-$SCIDB_VER-$PKG_VER.deb ;
    fi
  - docker exec deploy sh /this/try.sh

after_script:
  - docker stop script
  - docker stop deploy
