#!/bin/bash

scidbuser=`ps axfo user:64,cmd | grep scidb | grep dbname | head -n 1 | cut -d ' ' -f 1`
sed -i "s/LOGNAME/$scidbuser/" /var/lib/shim/conf
basepath=$(cat /opt/scidb/18.1/etc/config.ini | grep base-path | cut -d= -f2)
sed -i "s:\[INSTANCE_0_DATA_DIR\]:$basepath/0/0/tmp:" /var/lib/shim/conf
if test -f /etc/init.d/shimsvc; then /etc/init.d/shimsvc restart;fi
