#!/bin/bash

# Stop any existing service
# SystemD
if test -n "$(which systemctl 2>/dev/null)"; then
  systemctl -q stop shimsvc 2>/dev/null || true
# InitD Ubuntu
elif test -n "$(which update-rc.d 2>/dev/null)"; then
  service shimsvc stop 2>/dev/null||true
# InitD Fedora
elif test -n "$(which chkconfig 2>/dev/null)"; then
  service shimsvc stop 2>/dev/null||true
fi

if [ -z "$SCIDB_INSTALL_PATH" ]
then
    export SCIDB_INSTALL_PATH=/opt/scidb/XXX_SCIDB_VER_XXX
fi

$SCIDB_INSTALL_PATH/shim/after-install.sh
